blank_issues_enabled: false
contact_links:
  - name: Ask a Question or Get Help
    url: https://github.com/fyzanshaik/chaya-frontend/discussions
    email: fyzanshaik.work@gmail.com
    about: Please use GitHub Discussions for general questions or help.
